# ==============================================================================
# PostgreSQL Primary Role Configuration
# ==============================================================================
# Description: Specific tasks for configuring the primary node in the PG cluster.
#              - Ensures replication slots are present.
#              - Configures specific primary parameters if needed.
# ==============================================================================


- name: Create replication slots for standbys
  become_user: postgres
  postgresql_slot:
    name: "repmgr_slot_{{ hostvars[item].postgresql_id }}"
    slot_type: physical
    state: present
  loop: "{{ groups['db_nodes'] }}"
  when: 
    - postgresql_role == 'primary'
    - hostvars[item].postgresql_role == 'standby'
    - hostvars[item].postgresql_id is defined
