# ==============================================================================
# PostgreSQL Primary Role Configuration
# ==============================================================================
# Description: Specific tasks for configuring the primary node in the PG cluster.
#              - Ensures replication slots are present.
#              - Configures specific primary parameters if needed.
# ==============================================================================

- name: Ensure PostgreSQL service is started and enabled
  systemd:
    name: postgresql
    enabled: yes
    state: started
  when: postgresql_role == 'primary'

- name: Create replication slots (if configured)
  become_user: postgres
  postgresql_slot:
    name: "repmgr_slot_{{ item }}"
    slot_type: physical
    state: present
  loop: "{{ range(1, (postgresql.replication_slots | default(3)) + 1) | list }}"
  when: postgresql_role == 'primary'
