- name: restart chrony
  service:
    name: chrony
    state: restarted

- name: restart sshd
  service:
    name: ssh
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart affected services
  debug:
    msg: "System limits updated, some services might require restart to pick up changes"
