- name: restart postgres-exporter
  service:
    name: prometheus-postgres-exporter
    state: restarted

- name: restart nginx-exporter
  service:
    name: prometheus-nginx-exporter
    state: restarted

- name: restart node-exporter
  service:
    name: prometheus-node-exporter
    state: restarted
